name: covid_19
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 3.0.9
  cupertino_icons: ^0.1.2
  flutter_svg: 0.17.4
  flutter_platform_widgets: 0.32.5
  provider: 4.0.5+1
  get_it: 4.0.1
  injectable: 0.3.0
  connectivity: 0.4.8+5
  flushbar: 1.10.2
  intl: 0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  lint: 1.1.1
  injectable_generator: 0.3.4

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/Varela-Regular.ttf